FROM postgres:10.1-alpine

# SET ENV
ENV POSTGRES_DB acc_db
ENV POSTGRES_USER gismin
ENV POSTGRES_PASSWORD xYaXB3fDyUAN2hHnLJcj

# INITIAL TABLE
#ADD create_user_table.sql /docker-entrypoint-initdb.d/
